const fields=['caseName','caseFluid','casePin','casePout','caseFlow','caseTemp'];
const questions=['¿Qué ocurre aguas abajo si el regulador falla completamente abierto?','¿Calculaste el caudal real en el punto de menor presión?','¿Todos los componentes soportan la máxima presión creíble del sistema?','¿Cómo justificas el tamaño de tubing seleccionado?','¿La relief valve puede quedar aislada accidentalmente?','¿Qué efecto tiene Joule–Thomson sobre la temperatura mínima del sistema?','¿Tu selección considera condiciones dinámicas y no solo presión estática?'];
function getCase(){try{return JSON.parse(localStorage.capstoneCase||'{}')}catch{return {}}}
function loadCase(){const d=getCase();fields.forEach(id=>{const el=document.getElementById(id);if(el&&d[id])el.value=d[id]});renderAll(d)}
function saveCase(){const d={};fields.forEach(id=>{const el=document.getElementById(id);d[id]=el?el.value.trim():''});localStorage.capstoneCase=JSON.stringify(d);const m=document.getElementById('saveMsg');if(m)m.textContent='Guardado ✓';renderAll(d)}
function newCase(){if(confirm('¿Crear un caso nuevo? Se limpiarán los datos Capstone guardados localmente.')){['capstoneCase','capstoneFlowData','capstoneFluidFlow','capstoneLineSizing','capstoneLineInput','capstoneJT'].forEach(k=>localStorage.removeItem(k));location.reload()}}
function toggleCaseEdit(force){const el=document.getElementById('caseEditor');if(!el)return;el.hidden=typeof force==='boolean'?!force:!el.hidden}
function renderProcess(d={}){const el=document.getElementById('processSummary');if(!el)return;const vals=[d.casePin||'Pin','Regulation',d.casePout||'Pout'];el.innerHTML=vals.map((v,i)=>`${i?'<span class="process-arrow">→</span>':''}<span class="process-pill">${v}</span>`).join('')}
function renderCaseSummary(d={}){const el=document.getElementById('caseSummaryGrid');if(!el)return;const data=[['Nombre del caso',d.caseName||'Capstone Practice Case'],['Fluido',d.caseFluid||'No definido'],['Presión inlet',d.casePin||'—'],['Presión outlet',d.casePout||'—'],['Caudal requerido',d.caseFlow||'—'],['Temperatura',d.caseTemp||'—']];el.innerHTML=data.map(x=>`<div class="case-data"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}
function checklistData(d={}){const req=['caseFluid','casePin','casePout','caseFlow','caseTemp'];const complete=req.every(k=>d[k]);const flow=localStorage.capstoneFluidFlow==='done';const line=localStorage.capstoneLineSizing==='done';const jt=localStorage.capstoneJT==='done';return [[complete,'Project requirements',complete?'Definidos':'Completa datos base'],[flow,'Fluid properties & mass flow',flow?'Calculado':'Pendiente'],[flow,'P&ID / pressure points',flow?'Puntos definidos':'Pendiente'],[false,'Regulator sizing','Revisar en módulo'],[jt,'Joule–Thomson review',jt?'Revisado':'Pendiente'],[line,'Line sizing',line?'Cálculo realizado':'Pendiente'],[false,'Overpressure protection','Pendiente'],[false,'Failure analysis','Pendiente'],[false,'BOM & final review','Pendiente']]}
function renderChecklist(d={}){const el=document.getElementById('checklist');if(!el)return;const items=checklistData(d);el.innerHTML=items.map(x=>`<div class="check-item ${x[0]?'done':'warn'}"><i class="check-dot"></i><div><strong>${x[1]}</strong><small style="display:block;opacity:.65">${x[2]}</small></div></div>`).join('');const pct=Math.round(items.filter(x=>x[0]).length/items.length*100);const bar=document.getElementById('progressBar'),txt=document.getElementById('progressText');if(bar)bar.style.width=pct+'%';if(txt)txt.textContent=pct+'%'}
function renderModules(){const flow=localStorage.capstoneFluidFlow==='done',line=localStorage.capstoneLineSizing==='done',jt=localStorage.capstoneJT==='done';[['flow',flow],['jt',jt],['line',line]].forEach(([m,done])=>{const c=document.querySelector(`[data-module="${m}"]`);if(!c)return;c.classList.toggle('complete',done);const s=c.querySelector('.module-status');if(done){s.textContent='✓ Completado';s.className='module-status done'}else{s.textContent='Pendiente';s.className='module-status'}})}
function renderAll(d){renderCaseSummary(d);renderProcess(d);renderChecklist(d);renderModules()}
function nextQuestion(){const el=document.getElementById('reviewQ');if(el)el.textContent=questions[Math.floor(Math.random()*questions.length)]}
loadCase();nextQuestion();
