function toast(msg){let t=document.querySelector('.app-toast');if(!t){t=document.createElement('div');t.className='app-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2400)}
function showHelp(){toast('Ayuda: define → calculate → verify → justify. Documenta criterios y supuestos.')}
function showResources(){toast('Recursos técnicos: conecta aquí tus catálogos, sizing tools y documentación aprobada.')}
function openSettings(){toast('Configuración del workspace — preparada para una siguiente versión.')}
function openSavedCases(){toast('Los casos se guardan localmente en este navegador. Usa Exportar para respaldarlos.')}
function showMoreMenu(){toast('Más opciones: respaldo, impresión y revisión final estarán disponibles aquí.')}
function focusGlobalSearch(){const q=prompt('Buscar módulo o concepto:');if(!q)return;const x=q.toLowerCase();if(x.includes('flow')||x.includes('flu'))location.href='fluid-flow.html';else if(x.includes('reg'))location.href='regulator.html';else if(x.includes('joule')||x.includes('temp'))location.href='joule-thomson.html';else if(x.includes('line')||x.includes('tub'))location.href='line-sizing.html';else toast('No encontré un módulo coincidente.')}
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();focusGlobalSearch()}});
function exportCase(){const data={version:'4.0.0',exportedAt:new Date().toISOString(),case:JSON.parse(localStorage.capstoneCase||'{}'),fluidFlow:JSON.parse(localStorage.capstoneFlowData||'null'),lineInput:JSON.parse(localStorage.capstoneLineInput||'null'),status:{fluidFlow:localStorage.capstoneFluidFlow||'',lineSizing:localStorage.capstoneLineSizing||'',jouleThomson:localStorage.capstoneJT||''}};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=((data.case.caseName||'capstone-case').replace(/[^a-z0-9]+/gi,'-')+'.json');a.click();URL.revokeObjectURL(a.href);toast('Caso exportado.')}
function openCaseFile(){const i=document.getElementById('caseFileInput');if(i)i.click();else toast('Abrir caso está disponible desde Dashboard.')}
document.addEventListener('change',e=>{if(e.target.id!=='caseFileInput'||!e.target.files[0])return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d.case)localStorage.capstoneCase=JSON.stringify(d.case);if(d.fluidFlow)localStorage.capstoneFlowData=JSON.stringify(d.fluidFlow);if(d.lineInput)localStorage.capstoneLineInput=JSON.stringify(d.lineInput);if(d.status?.fluidFlow)localStorage.capstoneFluidFlow=d.status.fluidFlow;if(d.status?.lineSizing)localStorage.capstoneLineSizing=d.status.lineSizing;if(d.status?.jouleThomson)localStorage.capstoneJT=d.status.jouleThomson;location.reload()}catch{toast('El archivo no es un caso Capstone válido.')}};r.readAsText(e.target.files[0])});