const $=id=>document.getElementById(id);let seq=0;
const GAS={'Argon':{M:39.948,mu:.0225,rhoN:1.784},'Helium':{M:4.0026,mu:.0196,rhoN:.1785},'Nitrogen':{M:28.0134,mu:.0176,rhoN:1.2506},'Oxygen / GOX':{M:31.998,mu:.0202,rhoN:1.429},'Hydrogen':{M:2.0159,mu:.0088,rhoN:.0899}};
function refM3h(v,u){return u==='NLPS'?v*3.6:u==='NLPM'?v*.06:v}
function rhoIdeal(f,p,t){const g=GAS[f];if(!g)return null;return ((p+1.01325)*1e5)*(g.M/1000)/(8.314462618*(t+273.15))}
function addPoint(p={}){seq++;const tr=document.createElement('tr');tr.innerHTML=`<td><input class="pt-name" value="${p.name||'Point '+seq}"></td><td><input class="pt-p" type="number" step="0.1" value="${p.pressure??''}"></td><td><input class="pt-t" type="number" step="0.1" value="${p.temp??15}"></td><td><input class="pt-rho" type="number" step="0.001" value="${p.density??''}"></td><td class="pt-mass">—</td><td class="pt-flow">—</td><td><button class="mini-action send">Enviar a Line Sizing</button><button class="mini-action remove">×</button></td>`;$('pointsBody').appendChild(tr);tr.querySelector('.remove').onclick=()=>{tr.remove();calculate()};tr.querySelector('.send').onclick=()=>sendLine(tr)}
function show(ok,msg){$('flowStatus').className='status-banner '+(ok?'ok':'bad');$('flowStatus').textContent=msg}
function estimateProps(){const f=$('fluid').value,g=GAS[f];$('refDensity').value=g.rhoN;document.querySelectorAll('#pointsBody tr').forEach(tr=>{const r=rhoIdeal(f,+tr.querySelector('.pt-p').value,+tr.querySelector('.pt-t').value);if(r)tr.querySelector('.pt-rho').value=r.toFixed(3)});calculate();show(true,'✓ Propiedades estimadas para entrenamiento. Verifica los valores con una fuente validada para el caso real.')}
function calculate(){const v=+$('refFlow').value,rho0=+$('refDensity').value;if(!(v>0&&rho0>0)){show(false,'Ingresa caudal y densidad de referencia válidos.');return}const mass=refM3h(v,$('flowUnit').value)*rho0;let valid=0;document.querySelectorAll('#pointsBody tr').forEach(tr=>{const rho=+tr.querySelector('.pt-rho').value;tr.querySelector('.pt-mass').textContent=mass.toFixed(2);if(rho>0){const lpm=mass/rho*1000/60;tr.querySelector('.pt-flow').textContent=lpm.toFixed(2);tr.dataset.actual=lpm;valid++}else{tr.querySelector('.pt-flow').textContent='Falta densidad';tr.dataset.actual=''}});$('refOut').textContent=`${v} ${$('flowUnit').selectedOptions[0].text}`;$('massOut').textContent=mass.toFixed(2)+' kg/h';$('pointsOut').textContent=valid;$('statusOut').textContent=valid?'Calculado ✓':'Pendiente';show(valid>0,valid?`✓ Flujo másico calculado. ${valid} punto(s) tienen actual flow disponible.`:'Agrega al menos una densidad de línea.');save(mass);if(valid)localStorage.capstoneFluidFlow='done'}
function sendLine(tr){calculate();const actual=+tr.dataset.actual,rho=+tr.querySelector('.pt-rho').value;if(!(actual>0&&rho>0))return;const f=$('fluid').value;localStorage.capstoneLineInput=JSON.stringify({flow:actual,rho,pressure:+tr.querySelector('.pt-p').value,temp:+tr.querySelector('.pt-t').value,name:tr.querySelector('.pt-name').value,fluid:f,mu:GAS[f]?.mu||.02});location.href='line-sizing.html'}
function save(mass){const points=[...document.querySelectorAll('#pointsBody tr')].map(tr=>({name:tr.querySelector('.pt-name').value,pressure:+tr.querySelector('.pt-p').value,temp:+tr.querySelector('.pt-t').value,density:+tr.querySelector('.pt-rho').value,actual:+tr.dataset.actual||null}));localStorage.capstoneFlowData=JSON.stringify({fluid:$('fluid').value,refFlow:+$('refFlow').value,unit:$('flowUnit').value,refDensity:+$('refDensity').value,reference:$('reference').value,mass,points})}
function loadExample(){$('fluid').value='Argon';$('refFlow').value=5;$('flowUnit').value='NLPS';$('refDensity').value=1.78;$('pointsBody').innerHTML='';seq=0;[{name:'Bottle / inlet',pressure:250,temp:15,density:438.83},{name:'Intermediate',pressure:15,temp:15,density:27.01},{name:'Outlet max',pressure:11,temp:15,density:20.21},{name:'Outlet min',pressure:10,temp:15,density:18.51},{name:'Vent / atmospheric',pressure:0,temp:0,density:1.78}].forEach(addPoint);calculate()}
function init(){let d=null;try{d=JSON.parse(localStorage.capstoneFlowData||'null')}catch{};if(d){if(GAS[d.fluid])$('fluid').value=d.fluid;$('refFlow').value=d.refFlow||5;$('flowUnit').value=d.unit||'NLPS';$('refDensity').value=d.refDensity||GAS[$('fluid').value].rhoN;$('pointsBody').innerHTML='';seq=0;(d.points||[]).forEach(addPoint)}else{$('refDensity').value=GAS[$('fluid').value].rhoN;addPoint({name:'Inlet'});addPoint({name:'Intermediate'});addPoint({name:'Outlet'})}calculate()}
$('addRow').onclick=()=>addPoint();$('calculate').onclick=calculate;$('loadExample').onclick=loadExample;$('autoProps').onclick=estimateProps;$('fluid').onchange=()=>{$('refDensity').value=GAS[$('fluid').value].rhoN};init();